# @package _global_

slurm:
  job_name: diff_tta
  partition: kate_reserved # kate_reserved, deepaklong
  time: "24:00:00"
  gpus: 4
  mem_gb: 192GB
  cpus_per_task: 32
  n_processes: 1
  n_nodes: 1
  max_num_timeout: 100
  use_deepspeed: False
  exclude: null
  constraint: A100|6000ADA