SOLVER:
  IMS_PER_BATCH: 32
INPUT:
  MIN_SIZE_TRAIN: (256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640,)
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 4096
TEST:
  VISIBILITY_THRES: 0.33333333
  TRUNCATION_THRES: 0.33333333
DATASETS:
  TRAIN: ('KITTI_train', 'KITTI_val')
  TEST: ('KITTI_test',) 
  CATEGORY_NAMES: ('pedestrian', 'car', 'cyclist', 'van', 'truck', 'tram', 'person')
  IGNORE_NAMES: "['dontcare', 'ignore', 'void']"
  MIN_HEIGHT_THRES: 0.05
  TRUNCATION_THRES: 0.75
  VISIBILITY_THRES: 0.25
  TRUNC_2D_BOXES: True
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.1
VERSION: 2